COE-1034: add required files check before zipping

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,6 +44,14 @@ jobs:
       - name: Zip files for release
         run: |
           cd repo/simulators
+          if [[ ! -f image.tar ]]; then
+            echo "Missing required files: image.tar"
+            exit 1
+          fi
+          if [[ ! -f cumulocity.json ]]; then
+            echo "Missing required files: cumulocity.json"
+            exit 1
+          fi
           zip oee-simulators.zip image.tar cumulocity.json
 
       - name: Create Release
