COE-1034: add required files check before zipping (#94)
* COE-1034: add required files check before zipping

* COE-1034: use shell bash for zip step

---------

Co-authored-by: Nam Nhat Pham <naph@softwareag.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -42,8 +42,17 @@ jobs:
           docker rmi oee-simulators
 
       - name: Zip files for release
+        shell: bash
         run: |
           cd repo/simulators
+          if [[ ! -f image.tar ]]; then
+            echo "Missing required files: image.tar"
+            exit 1
+          fi
+          if [[ ! -f cumulocity.json ]]; then
+            echo "Missing required files: cumulocity.json"
+            exit 1
+          fi
           zip oee-simulators.zip image.tar cumulocity.json
 
       - name: Create Release
